### ISSUE TITLE
Saving display name doesn't

### ISSUE THREAD

**Issue by GeoNomad** [markthethomas/isbusy#2]
Despite entering just my first name before the calendar integration and after, the status page refuses to display the saved "display name".

**Comment by markthethomas** [comment]
@GeoNomad hey thanks for filing this! I'll take a look :)

**Comment by markthethomas** [comment]
@GeoNomad so I have a caching enabled in some places in order to reduce hits on APIs and I think what you were seeing was the cache not getting cleared. I've added a fix that should have just deployed :) when you update settings now, it clears your cache. Thanks and let me know if you have any other suggestions!
